### ISSUE TITLE
Issue with dwolla account creation

### ISSUE THREAD

**Issue by melinath** [dancerfly/django-brambling#823]
From a user:

> This may be an issue unique to me, but I was trying to pay for <event redacted> and the link provided for Dwolla did indeed let me set up an account, but I could not find out what my PIN was supposed to be.  When I got in touch with Dwolla support, they said that I had created an account that was limited to only receiving money and not sending it.  I just wanted to let you know in case your site had the wrong link.  Thanks!

We should look into this.

**Comment by micheleleah** [comment]
Another issue from a user:

>I've been trying very hard to use Dwolla to pay for my registration! Only, once I created my account, on Dancerfly it asks for my PIN, which I was never provided. I asked Dwolla for technical support, and they said a basic account does not have a PIN. And yet the Dancerfly registration will not accept it without a PIN :(

**Comment by melinath** [comment]
Another issue from a user (similar in that it's dwolla-related):

> I noticed I have $XXX of pending payments logged in XXXXX. It's all the Dwolla payments that have happened since the beginning of the year. If I go to my Dwolla account, they show transacted (and I have the $), however they don't show as completed in Dancerfly. I'd say this ranks pretty highly on the list of things that needs to be looked at if for no other reason than Dancerfly and Dwolla are clearly not talking to each other properly.

**Comment by raq929** [comment]
How are you testing dwolla things in the test environment? It's not showing up as an option for me to click on when I'm on the dev server.

**Comment by chigby** [comment]
Potentially relevant documentation: https://developers.dwolla.com/resources/account-types/access-api-accounts.html

**Comment by melinath** [comment]
Closing this - we're not going to fix it. We're going to remove dwolla.
