### ISSUE TITLE
Discontinue dwolla support

### ISSUE THREAD

**Issue by harrislapiroff** [dancerfly/django-brambling#901]
After a brief conversation with @melinath we have a tentative agreement to discontinue Dwolla support. Dwolla's fee structure is attractive to organizers, but the maintenance burden has been unwieldy for us. Until we implement this, it's still open for discussion.

**Comment by melinath** [comment]
The lw dwolla account is suspended; I don't think we ever set up an account for you. That means that dwolla is almost certainly broken.
