### ISSUE TITLE
Sunset DigitalOcean droplet

### ISSUE THREAD

**Issue by harrislapiroff** [dancerfly/django-brambling#905]
We migrated Dancerfly to Heroku! Yay! Unfortunately due to a complicated and unforeseen set of circumstances, we ended up leaving out old server up as a redirect from dancerfly.com to www.dancerfly.com. We should figure out a different way to handle that redirect (the server redirecting needs to support https!) and sunset our old friend the droplet.

**Comment by melinath** [comment]
We did sunset the LW droplet; this is still an issue but not as critical, I think.

**Comment by melinath** [comment]
This is also resolved - we use cloudfront for the lww/www.lww handling now.
