### ISSUE TITLE
Stop using zenaida hints

### ISSUE THREAD

**Issue by melinath** [dancerfly/django-brambling#918]
Currently we purport to use zenaida hints, but I'm not sure we ever actually implemented that. I don't _think_ it's a thing we care much about, in any case. If possible we should remove it as part of the project to remove zenaida as a dependency.

**Comment by harrislapiroff** [comment]
We use it for this message, but we could probably replace that pretty easily
<img width="1056" alt="screen shot 2019-01-23 at 8 13 47 pm" src="https://user-images.githubusercontent.com/296631/51647605-75bf7280-1f4b-11e9-9022-481caf4dc070.png">

**Comment by melinath** [comment]
Reading through the message, I don't think that it actually adds significant value - maybe we could just delete it?
