### ISSUE TITLE
Add file storage settings to staging environment

### ISSUE THREAD

**Issue by melinath** [dancerfly/django-brambling#925]
The staging environment is currently not fully functional, which means we can't actually use it to verify that code is behaving reasonably. In particular, right now it's getting errors because it can't write to the filesystem. We should give it access to a staging bucket in AWS. @harrislapiroff can you set that up?

This is high priority since it is preventing us from testing before pushing to production.

**Comment by harrislapiroff** [comment]
mrrr I wonder if we should be using [whitenoise](http://whitenoise.evans.io/en/stable/) for static files

**Comment by melinath** [comment]
This is resolved!
